### ISSUE TITLE
HPC everywhere: Suggestion to automatically set ccmrun if applicable 

### ISSUE THREAD

**Issue by agopu** [IUSCA/sca-issues#10]
Cross-linking to https://tickets.pti.iu.edu/Ticket/Display.html?id=209426 where Dr. Noah Stoffman had a suggestion for HPC everywhere: to automatically set ccmrun if applicable. 

We plan to implement this in the near future.

**Comment by agopu** [comment]
> Hi, it would be great if the script generator automatically added the line
> 
> #PBS -l gres=ccm
> 
> to scripts when neede, and either automatically added or reminded users to include ccmrun/aprun in their scripts.

This is an excellent idea! I've let him know we plan to implement this soon. And that we also plan to implement a "Script Doctor" feature that will alert users to possible error conditions that we've come across many times in the past.

**Comment by youngmd** [comment]
Added selection box to choose execution environment when Big Red 2 is the selected resource.  CCM is set as the default option.  When CCM is chosen the '-l gres=ccm' line is added to the output script.  On the Job Commands field a warning label is placed if 'ccmrun'/'aprun' are not detected in the entered commands (once the user has entered any text in the field).  See attached screenshot. 
 
![Screen Shot 2019-04-04 at 2 16 06 PM](https://user-images.githubusercontent.com/1247513/55578602-53349d00-56e4-11e9-97df-8da934eade3e.png)

**Comment by agopu** [comment]
Looks great, I briefly tested it on mike.sca...

**Comment by youngmd** [comment]
Since ccmrun requires that the ccm module be loaded I added a "module load ccm" command to appear in the module load section of the output if CCM env is the selected exec env.  I believe this is ready to push to production.

**Comment by youngmd** [comment]
This has been pushed to production.
