### ISSUE TITLE
OPS / RADL: Rebuild rtstats production and shift active site to new VM

### ISSUE THREAD

**Issue by rperigo** [IUSCA/sca-issues#11]
Creating this to allow non-SCA stakeholders to follow along on progress and comment while we roll this out.
Sister to: https://github.com/IUSCA/provision-int/issues/37 (internal)

Have spoken with Ben to orchestrate this. Prerequisites should hopefully be taken care of (or at least very nearly covered). Will begin staging code and data.

**Comment by rperigo** [comment]
Code and DBs are in place (with MySQL ACLs copied over). Will ping Ben in AM to start spooling services up and testing things.

**Comment by rperigo** [comment]
Oh, and SSL certs have been copied too. Looks like we need some Gem work to get the Rails app up :)

**Comment by rperigo** [comment]
Ben has gotten the code to run, I've checked that it's accessible and shows the proper content by assigning the stats1 ip to rtstats.uits.indiana.edu locally in my hosts file. Will do the final DNS changes / redump db, etc on Monday.

**Comment by agopu** [comment]
@rperigo confirmed everything was up and running on Monday.

This morning, with Ben's nod, I shut down the old stats VM. Per usual practices, I will leave the VM on I.I. for now in case we need to bring it back, and will delete it in a few weeks' time.
