### ISSUE TITLE
HPC Everywhere: My HPC comment

### ISSUE THREAD

**Issue by CicadaDennis** [IUSCA/sca-issues#17]
When I open this up. Since I have no jobs running, there are no jobs found. But then it is not clear what the button "Submit Job" is supposed to do. I can click it and nothing happens. Perhaps, if I had jobs already in the queue, would it do something? But what?

**Comment by CicadaDennis** [comment]
This is not an issue when I open from a local web browser. Was just the RED app running an old version of the application apparently. Clicking "Submit Job" opens a window to submit a job.

**Comment by agopu** [comment]
We're looking into the issue on RED on the other ticket you opened earlier; it should be sorted out by Monday.
