### ISSUE TITLE
open up RTStats to the world 

### ISSUE THREAD

**Issue by athota** [IUSCA/sca-issues#19]
Could you please open up rtstats.indiana.edu to the world? Thanks! 

Right now, this is accessible only from IU domains, but we would like these webpages to be available from outside IU domains.

**Comment by agopu** [comment]
Turned out, this was related to a recent RT ticket https://tickets.pti.iu.edu/Ticket/Display.html?id=209076 - we have discussed the issue further and addressed it. 

Please let us know if there are still any pending issues, Abhinav!
