### ISSUE TITLE
RTStats: Stop monitoring the top-level URL + monitor new web apps

### ISSUE THREAD

**Issue by benfulton** [IUSCA/sca-issues#21]
RTstats is no more! Please stop monitoring the URL https://rtstats.uits.indiana.edu/ as it is no longer in use. However, the following sub-URLS are still running and it would be nice to have them monitored:

https://rtstats.uits.indiana.edu/DLprojects
https://rtstats.uits.indiana.edu/HPCDashboard
https://rtstats.uits.indiana.edu/HPCDashboard2

Thanks!

**Comment by agopu** [comment]
Hi @benfulton we have updated our monitoring config to reflect the changes requested.

Note that in addition to https://rtstats.uits.indiana.edu/cluster_modules which is what we were monitoring (not the top level domain), I also removed https://rtstats-devel.uits.indiana.edu/cluster_modules ... so the only URLs we now monitor for RADL are the three you requested, checked once an hour with alerts going out to our slack channel you're part of.

FYI @rperigo.
