### ISSUE TITLE
Add user sagoll to the rtstats and rtstats-devel machines

### ISSUE THREAD

**Issue by benfulton** [IUSCA/sca-issues#22]
Please give our new hourly programmer access to the machines. Thanks!

**Comment by agopu** [comment]
@rperigo could you please take care of this? I will slack you her UID.

**Comment by agopu** [comment]
Actually, I will take care of this along with a couple of related cleanups.

@benfulton -- I've added the new user account, should her user account be part of the `hpc` group? 

I am assuming the usernames for Jerrin and Ramya should no longer be part of that group? Should their user accounts be removed too? (we always leave the home dirs intact, fwiw).

**Comment by benfulton** [comment]
Yes, add sagoll to the hpc group. Remove Jerrin's account but lets keep Ramya's for now just in case. Thanks!

**Comment by agopu** [comment]
Done.
