### ISSUE TITLE
Add a new website to rtstats and rtstats-devel

### ISSUE THREAD

**Issue by benfulton** [IUSCA/sca-issues#23]
Please modify the NginX config on these machines to allow access to 

https://rtstats.uits.indiana.edu/projects
https://rtstats-devel.uits.indiana.edu/projects

If these locations could serve a "Hello World" page that would be great :)

Thanks!

**Comment by agopu** [comment]
This is in place now. 

Spoke briefly with @benfulton - he plans to use a static page in the near future in place of the "under construction" page I put in place, and then to replace it with a web app later on (at which point he will contact us for further nginx updates).

**Comment by agopu** [comment]
The new site lives in `/web/projects` which you should be able to read/write into as your own username as via the group username y'all use.

**Comment by lamhuber** [comment]
From earlier, we would like to redirect incoming traffic from hpcprojects.uits.iu.edu to rtstats.uits.indiana.edu/projects while maintaining the hpcprojects.uits.iu.edu URL, and would like a cert for this new URL. Let me know if you need anything else from me! Many thanks!
