### ISSUE TITLE
Comments on current HPC Everywhere Beta

### ISSUE THREAD

**Issue by CicadaDennis** [IUSCA/sca-issues#24]
https://portal.ci.iu.edu/#/hpc
Some of the colors chosen for the categories (in Particular, looking at those on Karst and Carbonate), there are a few chose background colors are close to black, such that the text (which is printed in black) cannot be seen.

Not that big a deal, but the "< Back" Button does not always take one back to the previously viewed graph, but rather moves up the hierarchy of views. So if one clicks directly on a user from the view of the eintire Machine, clicking "< Back" takes one to the view of the Department, rather than back to the view of the whole machine.

The info on RED is incorrect (Probably we need to update the KB as well). 
There are a total of 26 agent nodes.
12 are Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
14 are Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz

https://portal.ci.iu.edu/#/software
When there is no search result, it would be good if something were printed, like:
"No Matches found"
I searched on "pcp" which exists as a module on both BR2 and Carbonate, but there was no match.
"r" also results in no response. Seems like anything less than 4 characters yields no results.

https://portal.ci.iu.edu/#/myhpc
When the search has no results, perhaps it could say something like
"No jobs found."

**Comment by agopu** [comment]
@youngmd had responded via email on Tuesday:
> Thank you Cicada.  I've addressed most of your feedback.  Couldn't do anything about the Back button on the chart, that functionality is built-in to the charting library. -Mike
