### ISSUE TITLE
RADL: Redirect hpcprojects.uits.iu.edu to rtstats/projects

### ISSUE THREAD

**Issue by lamhuber** [IUSCA/sca-issues#25]
Moving to a new issue for tracking purposes! From earlier, we would like to redirect incoming traffic from hpcprojects.uits.iu.edu to rtstats.uits.indiana.edu/projects while maintaining the hpcprojects.uits.iu.edu URL, and would like a cert for this new URL. Let me know if there is anything I can do on my end! Many thanks!

**Comment by agopu** [comment]
@lamhuber To clarify, when we talked in person the other day you specifically said you didn't want the URL to redirect... i.e the new URL should serve the traffic (served by rtstats/project) for requests coming to it. This is how we've configured things.

![image](https://user-images.githubusercontent.com/2206370/64353863-6d90e080-cfcc-11e9-87bc-5ac373e5a601.png)

Please confirm this is working fine; and also that existing RTStats URLs you guys expect to work are working fine too.

**Comment by lamhuber** [comment]
It is working great for me! Our other RTStats-related dependencies seem to be chugging along fine as well. Thank you!

**Comment by agopu** [comment]
Glad to hear! And you're welcome!

**Comment by lamhuber** [comment]
Could you also have that URL serve /web/DLProjects instead of /web/projects ? Many thanks!

**Comment by agopu** [comment]
I am getting a 403 now https://hpcprojects.uits.iu.edu ... 

There's a `/DLprojects` (lower case `p`) already configured, perhaps you wanted that? Note that it has a proxy pass, it's not serving a static web page.

**Comment by agopu** [comment]
Hi Laura,

> I am getting a 403 now https://hpcprojects.uits.iu.edu ...
> 
> There's a /DLprojects (lower case p) already configured, perhaps you wanted that? Note that it has a proxy pass, it's not serving a static web page.
> 

I've updated the nginx, instead, to serve the same `/DLprojects/` config previously available on the RTstats site so someone who goes to the URL does not get a 403. Please let me know if this is NOT what you want, and in that case please clarify what you do want to configured!

**Comment by agopu** [comment]
If we retain the updated config I setup, then let me strongly recommend you update the underlying web application to use the new URL instead of the RTstats one. Feel free to contact us if you need additional assistance.

**Comment by lamhuber** [comment]
Yeah, that's the one! That sounds ideal, thanks!
