### ISSUE TITLE
HPC everywhere job scheduler estimator

### ISSUE THREAD

**Issue by cganote** [IUSCA/sca-issues#29]
For Carbonate, debug/interactive queues aren't supported - do you want to leave them in there?

![image](https://user-images.githubusercontent.com/5487606/67486697-7ef48180-f63a-11e9-8118-e7e164f88dd2.png)

**Comment by agopu** [comment]
Hi @cganote , I would like @youngmd to correct me if I am mistaken but we get queue information directly from the job scheduler/manager, and I believe we are getting those queue names back. All of which _could_ be moot when we move to Slurm in the spring.

**Comment by youngmd** [comment]
Debug and Interactive queues are available on Carbonate.  It's just that the Backfill tool is not able to provide start time estimates for those queue.  But since they're almost always available it's kind of a moot point.

**Comment by agopu** [comment]
@cganote Does that make sense? Is there any other way we could assist with this?

**Comment by cganote** [comment]
It's fine to close this. I thought it looked weird, but it makes sense where it's coming from.

**Comment by agopu** [comment]
Thanks for getting back to us, @cganote!
