### ISSUE TITLE
VPN issues

### ISSUE THREAD

**Issue by benfulton** [IUSCA/sca-issues#33]
We need to get Matt Kusz (mkusz) access to the groups VPN. Scott M. tried doing it but was unsuccessful. If someone in our group could admin that list that would be nice. If they already can let me know - I couldn't figure it out :)

Scott also says he can't connect to the VPN.

**Comment by agopu** [comment]
Responded to Ben on Slack with the details. The RADL ADS group has all its full time staff members but not Matt, and is already configured to be admin'ed by Scott (or Robert Henschel); its members are inherited by their VPN ADS group. We have offered to yet add Matt if Ben/Scott need us to.

**Comment by agopu** [comment]
Turns out ADS needs an extra check box to be selected under the manager setting. Scott confirmed via Slack he is able to update the membership.
