### ISSUE TITLE
HPCe: Script Doctor bug for BR3 scripts

### ISSUE THREAD

**Issue by agopu** [IUSCA/sca-issues#34]
From Le Mai via Slack:

> The script doctor on hpceverywhere doesn't give me an error if I validate a BR3 job script requesting one node and more memory than is on a node
> 
> I was looking at RT ticket 228355 and noticed the script was made by HPCeverywhere.  The user is asking for 64gb which is more than the free memory on a node (hence the issue). But validating the job script with the doctor and tinkering with the mem option to request something like 128gb for one node doesn't throw an error
>

**Comment by agopu** [comment]
> Le Mai: The errors definitely showed up with faulty pbs scripts, but not with Slurm :slurm:

**Comment by youngmd** [comment]
This issue has been addressed in both the front-end script generator and the back-end python script doctor.  Memory limits for Big Red 3 have been set to 58GB (based on updated KB article: https://kb.iu.edu/d/aoku#jobs)
