### ISSUE TITLE
SPH-RSC: How to link dynamic data with Shiny app

### ISSUE THREAD

**Issue by StephanieD123** [IUSCA/sca-issues#35]
I was able to upload our app for our Whistle project:
https://rstudio.sca.iu.edu/connect/#/apps/17/access 

Now where/how can i upload the data as it updates every day or so to be used by the Shiny app.

**Comment by agopu** [comment]
Hi Stephanie,

Once again, congrats on publishing the Whistle project app!

We have several choices re: data updates:

1) You can setup the data downloads on our server with our assistance so the updated data get downloaded locally.

2) You can setup an rsync of data, once a day, from your server to ours with our assistance.

3) We can work with you to use a shared disk:
 a) Mounting your NFS server on our Shiny server.
 b) We can let you mount a local disk share on the Shiny server via SMB.
 c) Geode2 group storage mount that is mounted on our server for use by the Shiny app; you/others will push data to the same location as just you on your end.

The initial discussion regarding data storage needs had started with a need to access (read/write) it from your computers, our Shiny server AND from RED. Following our Zoom discussion we inferred you don't quite need to access it from RED which opens up the options above.

**Comment by StephanieD123** [comment]
Thanks Arvind. 

I’m CC’ing Xiwei if she has thoughts on preference, and she may correspond with you about options/directions.

 

You’re right that it looks like we probably don’t need RED. That was Scott Michael’s recommendation to make sure the correct R packages are available for the app, but as long as we can get the app to work I don’t think we need the data to connect to RED for now.

 

Thanks,
Stephanie

**Comment by agopu** [comment]
Hi Stephanie/Xiwei,

We know a lot is going on right now so no pressure but wanted to check if
you have further thoughts on how you want to proceed.

-a

**Comment by xinoooo** [comment]
Hi Arvind,

Thanks for listing us the options, but I don't understand the options quite well.

Maybe it would help by further explaining the situation we are facing:
This data is currently in a Dropbox folder and that folder would be updated manually by tech-people from the Whistle company daily. What we want to accomplish is that the Shiny app would always grab the latest version of data from the Dropbox folder(or from the server if we can copy/update the data from Dropbox to the server.) 

From my understanding, we need to publish the Shiny app daily (since the data updates every day) to show the latest information.  But I don't know how to automatically publish the Shiny app every day. Or do you have any better ideas on how to show the latest information on the Shiny app?

Thank you,
Xiwei
@StephanieD123 @agopu

**Comment by StephanieD123** [comment]
@agopu <https://github.com/agopu>  @xinoooo

Xiwei – I think that we shouldn’t need to re PUBLISH the app. 

I think that either:

1.     If the app can pull in the data from somewhere, then we just need to send the clean data to that spot every day to be read in by the app.

2.       Or, maybe if the app (or script on their server) can pull the data directly from its original source Dropbox and Fitbit (but I’m hesitant that this will work easily in a shared space with private API keys.

A few more details:

1.     There are Fitbit data (from human activity) which we download using the Fitbit API with Python code and then clean/rearrange and save the clean data

2.     There are Whistle data (tracking dogs activity) which the Whistle company puts in Dropbox and our Python code cleans and rearranges that and saves clean data .

3.     Right now, we are running scripts every day on Xiwei’s Mac to do these two pieces (which I think Xiwei has automated)

4.     Then both the clean Fitbit data and Whistle data are stored on Box, but we can put it anywhere you tell us to. 

The options you gave are:

1.     You can setup the data downloads on our server with our assistance so the updated data get downloaded locally.

2.     You can setup an rsync of data, once a day, from your server to ours with our assistance.

3.     We can work with you to use a shared disk:
a) Mounting your NFS server on our Shiny server.
b) We can let you mount a local disk share on the Shiny server via SMB.
c) Geode2 group storage mount that is mounted on our server for use by the Shiny app; you/others will push data to the same location as just you on your end.

Can you say more about how your options 1 to 3c will work with our needs. And what our “workflow” will look like as far as what we need to log-into and where our scripts and data would be stored and run.

 

Thanks!

Stephanie

**Comment by agopu** [comment]
Hi Stephanie and Xiwei,

Correct, you should not need to republish the app to pick up new data; the app should able to pick up fresh data from a designated data location. We just need to identify what location is optimally for this project.

> clean/rearrange and save the clean data

It is unclear how you clean/rearrange the Fitbit or Whistle data picked up by your automated scripts. Expanding on: 

- (Option 1) If this process is automated then we could simply setup the retrieval scripts and the cleanup/rearrange scripts on our server. I would guess that your API keys should still work unless they are tied to an IP address or some thing like that.
- (Option 2) We can assist you in setting up an rsync of *clean* Fitbit and Whistle data from whatever location on your end to our server. 
- (Option 3a) In lieu of needing to set up an rsync process, we could just mount your disk server on our server but this would not help with your Whistle data given it's on Box; we do not recommend mounting Box on the R-Studio Connect server but could try that too. 
- I would like to dissuade you from options 3b or 3c unless the options above are found to be infeasible.

I get the impression **option 2 would be the simplest so perhaps we should start with that** and see if it suffices? This way you can keep your existing data retrieval processes, and no administrative/operational changes need to made on any disk servers.

Please let us know. If a quick zoom call would help, we are happy to do that as well. Hope you all are safe at this time!

Best regards,
-a

**Comment by StephanieD123** [comment]
Hi Arvind, 

I agree that option 2 using rsync should be easiest to start. Please send directions and we’ll get started.

Thanks!

Stephanie

**Comment by agopu** [comment]
We are working with Stephanie, et al. off line to get them setup with the rsync'ing - will report back here when we are done.

**Comment by agopu** [comment]
As noted previously, we worked out details offline. Xiwei has access to our server to rysnc in the data from their end.

**Comment by rperigo** [comment]
Hi all - Bringing everyone back into the loop now that updated data has been placed on the server.

The data on the RSC server lives in the directory:

`/opt/sca/sphdata`

It is owned by the group account `sphrsc`, which is the same user running the Shiny applications within RStudio Connect - we will have to verify this, but once the Shiny apps are updated to use this directory when executed on the server, it should have access to that data directory. If not, we can help debug. It will probably be necessary to add some logic to the Shiny applications such that they are able to tell if they are running on the production machine or not (perhaps a hostname check or some such would suffice).

**Comment by agopu** [comment]
@StephanieD123 @xinoooo -- With the rsync in place, could we confirm that your app has the dynamic data you requested on this ticket? i.e could we close out this ticket?

**Comment by StephanieD123** [comment]
Hi – It doesn’t seem to be working. 

https://rstudio.sca.iu.edu/connect/#/apps/19/access

Am I missing something? Does it work for you?

**Comment by agopu** [comment]
> Hi – It doesn’t seem to be working.

@StephanieD123 @xinoooo I was talking with @rperigo a while back and he mentioned there is character encoding issues in the data that is causing errors. **Could Xiwei please open a new ticket to follow up on that?** It's not a problem with the the data setup as much as it is a problem with the data itself. Thanks!

**Comment by rperigo** [comment]
To elucidate on that - I added some print statements to log the contents of the `fitbit_var` and `study_id` variables taken from the data files. This resulted in the following log additions:

```
2020/04/09 20:30:42.688645690 [1] "steps"                "calories"             "caloriesBMR"        
2020/04/09 20:30:42.688669697 [4] "distance"             "minutesSedentary"     "minutesLightlyActive"
2020/04/09 20:30:42.688771910 [7] "minutesFairlyActive"  "minutesVeryActive"    "activityCalories"   
2020/04/09 20:30:42.916269387 # A tibble: 11 x 10
2020/04/09 20:30:42.916285369    `Subject ID` `Accelerometer âŠ `Randomization âŠ Group `Fitbit email`
2020/04/09 20:30:42.916353422           <dbl> <lgl>                       <dbl> <chr> <lgl>        
2020/04/09 20:30:42.916364871  1            1 NA                              1 FitbâŠ NA           
2020/04/09 20:30:42.916382868  2            2 NA                             NA <NA>  NA           
2020/04/09 20:30:42.916384426  3            3 NA                              2 ContâŠ NA           
2020/04/09 20:30:42.916401518  4            4 NA                              3 FitbâŠ NA           
2020/04/09 20:30:42.916403098  5            5 NA                              4 FitbâŠ NA           
2020/04/09 20:30:42.916437535  6            6 NA                              5 FitbâŠ NA           
2020/04/09 20:30:42.916439039  7            7 NA                              6 FitbâŠ NA           
2020/04/09 20:30:42.916456071  8            8 NA                              7 F+W   NA           
2020/04/09 20:30:42.916457576  9            9 NA                              8 FitbâŠ NA           
2020/04/09 20:30:42.916475081 10           10 NA                              9 F+W   NA           
2020/04/09 20:30:42.916476526 11           11 NA                             10 WhisâŠ NA           
2020/04/09 20:30:42.916495271 # âŠ with 5 more variables: `Fitbit code` <chr>, `Whistle serial #` <chr>, `Dog
2020/04/09 20:30:42.916496822 #   ID` <dbl>, `Accelerometer Post` <lgl>, notes <chr>


```
It does appear the files are at least accessible to the application. However, the garbage characters above and the lines:
```
2020/04/09 19:56:13.884623871 Warning in force(expr) : input string 'é' cannot be translated to UTF-8, is it valid in 'ANSI_X3.4-1968'?
2020/04/09 19:56:13.884711497 Warning in force(expr) : input string 'é' cannot be translated to UTF-8, is it valid in 'ANSI_X3.4-1968'?
2020/04/09 19:56:13.885044413 Warning in force(expr) : input string 'é' cannot be translated to UTF-8, is it valid in 'ANSI_X3.4-1968'?
```
lead me to believe there may be an encoding issue. It could be something else, but it definitely appears to be in the way R is ingesting the data. The cause for the error message onscreen appears to be that the plot function cannot get proper values for X axis.

```
2020/04/10 16:14:29.889871963 Warning: Length of logical index must be 1 or 11, not 0
2020/04/10 16:14:29.896927937 Warning: Error in if: argument is of length zero
2020/04/10 16:14:29.907056554   180: PlotSubject
2020/04/10 16:14:29.907065427   179: renderPlot [/opt/rstudio-connect/mnt/app/app.R#102]
2020/04/10 16:14:29.907107400   177: func
2020/04/10 16:14:29.907109454   137: drawPlot
2020/04/10 16:14:29.907126694   123: <reactive:plotObj>
2020/04/10 16:14:29.907128292   107: drawReactive
2020/04/10 16:14:29.907144866    94: origRenderFunc
2020/04/10 16:14:29.907146463    93: output$PlotSubject
2020/04/10 16:14:29.907162763    13: runApp
2020/04/10 16:14:29.907164372    12: fn
2020/04/10 16:14:29.907189844     7: connect$retry
2020/04/10 16:14:29.907191996     6: eval
2020/04/10 16:14:29.907229365     5: eval
2020/04/10 16:14:30.000214436 Warning in min(x) : no non-missing arguments to min; returning Inf
2020/04/10 16:14:30.000632994 Warning in max(x) : no non-missing arguments to max; returning -Inf
2020/04/10 16:14:30.022418103 Warning: Error in plot.window: need finite 'xlim' values
```

**Comment by StephanieD123** [comment]
Xiwei says she’s working on it. The data format changed from the Whistle people, so we need to adjust. So we can’t test the “dynamic data” part until we get that settled. Thanks for understanding – lots of moving parts. 
It’s also not dynamic yet until we set a script to run rsync every day. But I think we can do that.

**Comment by agopu** [comment]
Sounds good, we will stay tuned!

**Comment by agopu** [comment]
Following up on the new ticket linked above: https://github.com/IUSCA/sca-issues/issues/38
