### ISSUE TITLE
Shiny apps not working from home (with VPN)

### ISSUE THREAD

**Issue by StephanieD123** [IUSCA/sca-issues#36]
Hi- 
The Shiny apps i made are not working for me from home even though I'm connected with VPN.
https://rstudio.sca.iu.edu/connect/#/apps/17/access
It says "The application failed to start (exited with code 1)."
"2020/03/24 18:33:54.652150467 24 Mar 2020 18:33:54 [rsandbox] ERROR Directory /tmp/sqlite doesn't exist; LOGGED FROM: rstudio::core::ProgramStatus rstudio::sandbox::Options::read(int, char* const*) /var/lib/jenkins/workspace/IDE/monitor/src/cpp/server/sandbox/SandboxOptions.cpp:112"
Thanks,
Stephanie

**Comment by rperigo** [comment]
Hi Stephanie,

Can you try again? For some reason that directory was removed and RSC refuses to recreate it.

- Ray

**Comment by StephanieD123** [comment]
Yes, it worked this time. Thank you.
