### ISSUE TITLE
Install openldap-devel on rtstats-devel

### ISSUE THREAD

**Issue by benfulton** [IUSCA/sca-issues#44]
Trying to "pip3 install python-ldap" gives the following error:

 Modules/common.h:15:18: fatal error: lber.h: No such file or directory

I think this is from openldap-devel. Could it be added?

Thanks!

**Comment by rperigo** [comment]
`openldap-devel` is installed, and it does indeed provide that header file.

**Comment by benfulton** [comment]
Looks good, thanks!
