### ISSUE TITLE
Add a new website (rtstatus.uits.iu.edu) to rtstats

### ISSUE THREAD

**Issue by lamhuber** [IUSCA/sca-issues#45]
A little while ago, we set up a new DNS entry for rtstatus.uits.iu.edu with IP 129.79.72.221. We're setting up a site that will be sitting at /web/rtstatus on the production RTStats machine. Would it be possible to direct the URL rtstatus.uits.iu.edu to serve content at /web/rtstatus ? The content there should be structured pretty similarly to the /web/dl-user-index content that hpcprojects.uits.iu.edu directs to, therefore we'll need two available ports, one for the React client and one for the Node server backend. 

Thanks!

**Comment by agopu** [comment]
@lamhuber Thank you for clarifying a couple of details over Slack on Friday. We've modified the DNS entry so it's a CNAME and not a separate IP. Nonetheless we are still uncertain how you would like us to set this up. There is no `/web/dl-user-index` for example currently. Let me suggest you go ahead and run the web app (UI and API) as the designated user on your own from the commandline (and using ports I will share separately), get it working and ensure everything works and we can bring it all into the PM2 umbrella when everything is set. How does that sound?

**Comment by agopu** [comment]
Laura got back to me with further details on Slack. This is all sorted out now, the service is up and running.
