### ISSUE TITLE
Upgrade rtstats-devel java to Java 11

### ISSUE THREAD

**Issue by benfulton** [IUSCA/sca-issues#46]
Jenkins is giving a warning: _Java 11 is the recommended version to run Jenkins on; please consider upgrading._

We should do that :) No hurry, next time maintenance is done on that machine would be fine,

Thanks!

**Comment by agopu** [comment]
Our audit logs have shown some jenkins weirdness (it keeps trying to access stuff it shouldn't)... perhaps this will help. We will get on it ASAP.

**Comment by agopu** [comment]
@benfulton I've installed this.

Currently it's at `/usr/lib/jvm/java-11-openjdk-11.0.12.0.7-0.el7_9.x86_64/bin/java` 
```
[root@dev ~]#  /usr/lib/jvm/java-11-openjdk-11.0.12.0.7-0.el7_9.x86_64/bin/java -version
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode, sharing)
```

Would you like it to be the default java? Currently, the default version is still Java 8.

```
[root@dev ~]# java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

**Comment by benfulton** [comment]
Yes, but maybe not on a Friday afternoon :) At some point Jenkins will need to be restarted to pick up the new Java and that may cause some issues.

**Comment by agopu** [comment]
Ha! Of course ... ok let's follow up next week.

**Comment by agopu** [comment]
This got back-burnered earlier in the week but the default java version swap is complete. We did a full OS update while we were at it and rebooted the server w/ Ben's nod. The newer versions of Jenkins since mid Jul have been doing some weird things trying to identify rogue processes in turn triggering augit log errors. We will follow up elsewhere and when we can.
