### ISSUE TITLE
EMC: Trouble with SMB mount of DCWAN on microscope computer

### ISSUE THREAD

**Issue by dagmorga** [IUSCA/sca-issues#6]
I tried to mount the `\\10.xx\dcwan` mount on both the DE64 camera server (where it used to work) and on the Falcon camera server, but it didn't work in either location.  The DE64 camera has been out of the microscope since before Christmas (until late yesterday), so I can't tell you when that mount last worked.

I rebooted the box you left that should be taking care of this but no change.  I was able to mount the geode mount (`\\rsgwi0.mort*.xx\\\<xyz>\emcuser`) on several boxes using the `emcuser` and password that I thought was correct.

(Note: updated for clarify and to obfuscate a couple of details.)

**Comment by agopu** [comment]
Hi David,

I spent an hour jogging my memory via old notes, etc. and then investigating this issue. I can confirm being unable to SMB mount DCWAN from that box on my VPN-connected laptop as well. We will continue to look into this and get back to you as soon as we have any news.

Thanks,
-a

**Comment by dagmorga** [comment]
?Thanks.


--
    politics is more difficult than physics.
                                             A. Einstein

            David Gene Morgan
        Electron Microscopy Center
             047D Simon Hall
             IU Bloomington
          812 856 1457 (office)
          812 856 3221 (3200)
      http://iubemcenter.indiana.edu
________________________________

**Comment by agopu** [comment]
Hi David, I dug into this further without much luck. Then Ray reminded me we had specifically set it up with a certain security assumption. I still could not login but the issue at that point was on my Windows 10 laptop. I will send you an email offline about this and hopefully you will be all set.

**Comment by agopu** [comment]
Follow-up instructions did not end up enabling a successful mount on David's end but we believe the issue now is updated client network configuration. We are continuing to follow up with David via email (and documenting those correspondences in int-issues 31.

**Comment by agopu** [comment]
Today's updates to the SMB export box did he trick, David has confirmed being able to mounted DCWAN on the client boxes he wants to do this on. Closing this ticket.
