### ISSUE TITLE
CMS-E: Request to install additional R packages 

### ISSUE THREAD

**Issue by informaticianme** [IUSCA/sca-issues#8]
Updated by agopu. -2019-03-12

Apologies if this is redundant. I'm creating an issue in our `sca-issues` repo just as a means to make certain the issue is being handled / will be resolved. (Not sure exactly what I may end up helping with in the future so I'm just trying to track what comes through that I may eventually need to help with).

I see this was mailed to the sca-group list and is addressed to Ray. @rperigo, is this something you're already handling? Let me know if there's anything I can / should help with.

-----

Cross-linking https://tickets.pti.iu.edu/Ticket/Display.html?id=208617 - Ray will follow up on RT for now. -agopu

**Comment by rperigo** [comment]
Per ticket, these are all installed.
