### ISSUE TITLE
Add cicada/rthpcmon account to rtstats-devel

### ISSUE THREAD

**Issue by benfulton** [IUSCA/sca-issues#9]
Cicada would like to move his cron scripts off of sciapt-prod-1. They do a lot of ssh for data collection, and make ssh calls without specifying a username. Can the rthpcmon account be added to rtstats-devel.uits.indiana.edu so the scripts can more easily be copied over?

**Comment by rperigo** [comment]
This is done (both users added to group `hpc` as well)

**Comment by rperigo** [comment]
This has been done. Please let me know if there are further issues from your / Cicada's end with his scripts.
